// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCredential(arg1) {
  return window['go']['main']['App']['AddCredential'](arg1);
}

export function GetCredential(arg1) {
  return window['go']['main']['App']['GetCredential'](arg1);
}

export function GetDownloadsPath() {
  return window['go']['main']['App']['GetDownloadsPath']();
}

export function ListCredentials() {
  return window['go']['main']['App']['ListCredentials']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
