// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { credentials } from '../models';
import { settings } from '../models';

export function AddCredential(arg1: credentials.Credential): Promise<void>;

export function GetCredential(arg1: number): Promise<credentials.Credential>;

export function GetDownloadsPath(): Promise<string>;

export function GetSettings(): Promise<settings.Settings>;

export function ListCredentials(): Promise<Array<credentials.Credential>>;

export function SaveFile(arg1: string, arg2: Array<number>): Promise<void>;

export function UpdateSettings(arg1: settings.Settings): Promise<void>;

export function Version(): Promise<string>;
