// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {credentials} from '../models';

export function AddCredential(arg1:credentials.Credential):Promise<void>;

export function GetCredential(arg1:number):Promise<credentials.Credential>;

export function GetDownloadsPath():Promise<string>;

export function ListCredentials():Promise<Array<credentials.Credential>>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;

export function Version():Promise<string>;
